name: Project Def
params:
  - name: Cost Center
    type: number
    default: 4711
    allowed:
      - 4711
      - 8153

  - name: Data Classification
    type: string
    default: Internal
    allowed:
      - Public
      - Internal
      - Confidential
