name: Project Def

description: ./README.md

components:
  - github.repos.repo.*

parameters:
  - id: costCenter
    name: Cost Center
    type: string
    default: 4711
    allowed:
      - 4711
      - 8153

  - id: dataClassification
    name: Data Classification
    type: string
    default: Internal
    allowed:
      - Public
      - Internal
      - Confidential
